#####################################################################
###########     configuration file to predict quarry     ############ 
#####################################################################
# Follow the workflow to predict quarries in a given area of interest
# Refer to the README.md provided for more details


# 1-Prepare the tiles geometry according to the AOI and zoom level
prepare_data.py: 
  srs: "EPSG:2056"                       # Projection of the input file
  datasets:
    labels_shapefile: ../input/input-prd/[AOI_Shapefile]
  output_folder: ../output/output-prd
  zoom_level: 16    #z, keep between 15 and 18  

# 2-Request tiles according to the provided AOI and tiles parameters
generate_tilesets.py:
  debug_mode: 
    enable: False                  # Enable to work on a subset of tiles 
    nb_tiles: 2000
  empty_tiles:
    add_tiles: False              # Keep false for prediction  
  datasets:
    aoi_tiles_geojson: ../output/output-prd/tiles.geojson
    orthophotos_web_service:
      type: XYZ # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ
      url: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/2020/3857/{z}/{x}/{y}.jpeg
  output_folder: ../output/output-prd
  tile_size: 256 # per side, in pixels
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Quarry and exploitation site detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:
    category:
        name: "Quarry"
        supercategory: "Land usage"

# 3-Perform the object detection based on the optimized trained model
make_predictions.py:
  working_folder: ../output/output-prd
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files: # relative paths, w/ respect to the working_folder
      oth: COCO_oth.json
  detectron2_config_file: '../../config/detectron2_config_dqry.yaml' # path relative to the working_folder
  model_weights:
      pth_file: '../../output/output-trne/logs/model_model_0002999.pth'    #!!!Chose the optimized trained model, i.e. the one minimizing the validation loss curve 
  image_metadata_json: '../output/output-prd/img_metadata.json'
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: True
    epsilon: 2.0 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.3

# 4-Filtering and merging prediction polygons to improve results
prediction_filter.py:
  year: 2020
  input: ../output/output-prd/oth_predictions_at_0dot3_threshold.gpkg
  labels_shapefile: ../input/input-prd/[AOI_Shapefile]
  dem: ../input/input-prd/switzerland_dem_EPSG2056.tif
  elevation: 1200.0     #m, altitude threshold. Dectection above the threshold are discarded. Unlikely to observe quarry above and avoid flase detection of rock outcrop and snow . Default: 1200
  score: 0.95          #prediction score (reliability of the detection) provided by detectron2. The value can be varied from 0 to 1. Default: 0.95 
  distance: 10          #m, distance use as a buffer to merge close polygons (likely to belong to the same quarry) together. Default: 10
  area: 5000.0          #m2, area threshold under which polygons are discarded (unlikely to observe quarry sites under this surface). Default: 5000.0
  output: ../output/output-prd/oth_prediction_at_0dot3_threshold_year-{year}_score-{score}_area-{area}_elevation-{elevation}_distance-{distance}.geojson